apiVersion: chaos.havock8s.io/v1alpha1
kind: Havock8sExperiment
metadata:
  name: test-pod-failure
  namespace: test
spec:
  target:
    name: test-pod
    namespace: test
  chaosType: PodFailure
  duration: 30s
  intensity: 1 