---
apiVersion: v1
kind: Namespace
metadata:
  name: havock8s-system
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: havock8sexperiments.chaos.havock8s.io
spec:
  group: chaos.havock8s.io
  names:
    kind: Havock8sExperiment
    listKind: Havock8sExperimentList
    plural: havock8sexperiments
    singular: havock8sexperiment
    shortNames:
      - sce
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
      - name: Type
        type: string
        jsonPath: .spec.chaosType
        description: Type of chaos
      - name: Target
        type: string
        jsonPath: .spec.target.targetType
        description: Target type
      - name: Phase
        type: string
        jsonPath: .status.phase
        description: Experiment phase
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - target
                - chaosType
                - duration
                - intensity
              properties:
                target:
                  type: object
                  properties:
                    selector:
                      type: object
                      properties:
                        matchLabels:
                          type: object
                          additionalProperties:
                            type: string
                      nullable: true
                    name:
                      type: string
                    namespace:
                      type: string
                    targetType:
                      type: string
                      enum:
                        - StatefulSet
                        - Deployment
                        - Pod
                        - PersistentVolume
                        - PersistentVolumeClaim
                        - Service
                    mode:
                      type: string
                      enum:
                        - One
                        - All
                        - Random
                        - Percentage
                        - Fixed
                    value:
                      type: string
                chaosType:
                  type: string
                  enum:
                    - DiskFailure
                    - NetworkLatency
                    - DatabaseConnectionDisruption
                    - PodFailure
                    - ResourcePressure
                    - DataCorruption
                    - StatefulSetScaling
                duration:
                  type: string
                  pattern: ^([0-9]+h)?([0-9]+m)?([0-9]+s)?$
                intensity:
                  type: number
                  minimum: 0
                  maximum: 1
                parameters:
                  type: object
                  additionalProperties:
                    type: string
                schedule:
                  type: object
                  properties:
                    cron:
                      type: string
                    immediate:
                      type: boolean
                    once:
                      type: boolean
                safety:
                  type: object
                  properties:
                    autoRollback:
                      type: boolean
                    healthChecks:
                      type: array
                      items:
                        type: object
                        required:
                          - type
                        properties:
                          type:
                            type: string
                          path:
                            type: string
                          port:
                            type: integer
                            format: int32
                          command:
                            type: array
                            items:
                              type: string
                          failureThreshold:
                            type: integer
                            format: int32
                    pauseConditions:
                      type: array
                      items:
                        type: object
                        required:
                          - type
                        properties:
                          type:
                            type: string
                          metricQuery:
                            type: string
                          threshold:
                            type: string
                    resourceProtections:
                      type: array
                      items:
                        type: object
                        required:
                          - type
                          - value
                        properties:
                          type:
                            type: string
                            enum:
                              - Namespace
                              - Label
                              - Annotation
                              - Name
                          value:
                            type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                startTime:
                  type: string
                  format: date-time
                endTime:
                  type: string
                  format: date-time
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                targetResources:
                  type: array
                  items:
                    type: object
                    required:
                      - kind
                      - name
                    properties:
                      kind:
                        type: string
                      name:
                        type: string
                      namespace:
                        type: string
                      uid:
                        type: string
                      status:
                        type: string
                failureReason:
                  type: string
      subresources:
        status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: havock8s-controller-manager
  namespace: havock8s-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: havock8s-manager-role
rules:
- apiGroups:
  - chaos.havock8s.io
  resources:
  - havock8sexperiments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - chaos.havock8s.io
  resources:
  - havock8sexperiments/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - chaos.havock8s.io
  resources:
  - havock8sexperiments/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - core
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core
  resources:
  - services
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: havock8s-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: havock8s-manager-role
subjects:
- kind: ServiceAccount
  name: havock8s-controller-manager
  namespace: havock8s-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: havock8s-controller-manager
  namespace: havock8s-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: havock8s-controller-manager
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: havock8s-metrics-service
  namespace: havock8s-system
  labels:
    app: havock8s-controller-manager
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  selector:
    app: havock8s-controller-manager 