apiVersion: chaos.statefulchaos.io/v1alpha1
kind: StatefulChaosExperiment
metadata:
  name: redis-network-latency
spec:
  target:
    selector:
      matchLabels:
        app: redis
    targetType: StatefulSet
    mode: All
  chaosType: NetworkLatency
  duration: 10m
  intensity: 0.5  # 50% impact
  parameters:
    latency: "200ms"     # add 200ms of latency
    jitter: "50ms"       # with 50ms of jitter
    correlation: "75%"   # 75% correlation between packets
    ports: "6379,6380"   # affect only Redis ports
  schedule:
    cron: "0 */2 * * *"  # Every 2 hours
  safety:
    autoRollback: true
    healthChecks:
      - type: tcpSocket
        port: 6379
        failureThreshold: 5
    pauseConditions:
      - type: metric
        metricQuery: "sum(rate(redis_connection_errors_total[1m])) > 5" 