theme: jekyll-theme-cayman
title: Havock8s Documentation
description: A cloud-native chaos engineering framework for stateful applications on Kubernetes
baseurl: "/havock8s"
url: "https://docs.havock8s.io"
show_downloads: true
github:
  repository_url: https://github.com/samsonkolge/havock8s
  zip_url: https://github.com/samsonkolge/havock8s/archive/main.zip
  tar_url: https://github.com/samsonkolge/havock8s/archive/main.tar.gz
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
defaults:
  - scope:
      path: ""
    values:
      layout: "default" 