name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: make build

    - name: Run Tests
      run: make test

    - name: Verify Go Modules
      run: |
        go mod tidy
        git diff --exit-code go.mod go.sum

    - name: Run go vet
      run: go vet ./... 